steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Log in to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  - name: Build and push Docker image
    run: |
      docker build -t ${{ secrets.DOCKER_USERNAME }}/url-shortener:latest ./Project-2
      docker push ${{ secrets.DOCKER_USERNAME }}/url-shortener:latest

