version: 0.2

env:
  variables:
    IMAGE_NAME: "sample-python-flask-app"
  secrets-manager:
    DOCKER_REGISTRY_USERNAME: dockerhub-build:DOCKER_REGISTRY_USERNAME
    DOCKER_REGISTRY_PASSWORD: dockerhub-build:DOCKER_REGISTRY_PASSWORD

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $IMAGE_NAME .

  post_build:
    commands:
      - echo "Tagging and pushing image..."
      - docker tag $IMAGE_NAME pranam2835/sample-python-flask-app:latest
      - docker push pranam2835/sample-python-flask-app:latest

artifacts:
  files:
    - '**/*'
