version: 0.2

env:
  variables:
    IMAGE_NAME: pranam2835/sample-python-flask-app
    TAG: latest
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub-build:username
    DOCKERHUB_PASSWORD: dockerhub-build:password

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME:$TAG ./day-14/sample-python-app

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $IMAGE_NAME:$TAG
      - echo Done.
