version: 0.2

env:
  variables:
    IMAGE_NAME: yourdockerhubusername/yourimagename
    TAG: latest
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub-creds:username
    DOCKERHUB_PASSWORD: dockerhub-creds:password

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME:$TAG .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $IMAGE_NAME:$TAG
      - echo Done.
